[package]
name = "cilada-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
log = "0.4.22"
env_logger = "0.11.5"
rand = "0.9.0-alpha.2"
clap = { version = "4.5.20", features = ["derive"] }
